Return-Path: <bounce-nbd=lists+nbd=lfdr.de@other.debian.org>
X-Original-To: lists+nbd@lfdr.de
Delivered-To: lists+nbd@lfdr.de
Received: from bendel.debian.org (bendel.debian.org [82.195.75.100])
	by mail.lfdr.de (Postfix) with ESMTPS id C1EA38316C7
	for <lists+nbd@lfdr.de>; Thu, 18 Jan 2024 11:46:56 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
	by bendel.debian.org (Postfix) with QMQP
	id 6F1BE207AD; Thu, 18 Jan 2024 10:46:56 +0000 (UTC)
X-Mailbox-Line: From nbd-request@other.debian.org  Thu Jan 18 10:46:56 2024
Old-Return-Path: <roker@pep-project.org>
X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on bendel.debian.org
X-Spam-Level: 
X-Spam-Status: No, score=-15.8 required=4.0 tests=KHOP_HELO_FCRDNS,
	LDOSUBSCRIBER,LDO_WHITELIST,PGPSIGNATURE,T_SCC_BODY_TEXT_LINE
	autolearn=unavailable autolearn_force=no version=3.4.2
X-Original-To: lists-other-nbd@bendel.debian.org
Delivered-To: lists-other-nbd@bendel.debian.org
Received: from localhost (localhost [127.0.0.1])
	by bendel.debian.org (Postfix) with ESMTP id ED549207A6
	for <lists-other-nbd@bendel.debian.org>; Thu, 18 Jan 2024 10:46:44 +0000 (UTC)
X-Virus-Scanned: at lists.debian.org with policy bank en-lt
X-Amavis-Spam-Status: No, score=-12.009 tagged_above=-10000 required=5.3
	tests=[BAYES_00=-2, KHOP_HELO_FCRDNS=0.001, LDO_WHITELIST=-5,
	PGPSIGNATURE=-5, T_SCC_BODY_TEXT_LINE=-0.01]
	autolearn=ham autolearn_force=no
Received: from bendel.debian.org ([127.0.0.1])
	by localhost (lists.debian.org [127.0.0.1]) (amavisd-new, port 2525)
	with ESMTP id dTVUc7nzYbXc for <lists-other-nbd@bendel.debian.org>;
	Thu, 18 Jan 2024 10:46:41 +0000 (UTC)
X-policyd-weight: using cached result; rate: -4.6
Received: from pibit.ch (dragon.pibit.ch [185.203.114.4])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
	(Client did not present a certificate)
	by bendel.debian.org (Postfix) with ESMTPS id 1655E207A5
	for <nbd@other.debian.org>; Thu, 18 Jan 2024 10:46:41 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by dragon.pibit.ch (Postfix) with ESMTP id 41F092140270
	for <nbd@other.debian.org>; Thu, 18 Jan 2024 11:46:38 +0100 (CET)
Received: from pibit.ch ([127.0.0.1])
 by localhost (dragon.pibit.ch [127.0.0.1]) (amavis, port 10024) with ESMTP
 id El37OqiCinUj for <nbd@other.debian.org>;
 Thu, 18 Jan 2024 11:46:38 +0100 (CET)
Received: from 127.0.0.1 (pd9e55c12.dip0.t-ipconnect.de [217.229.92.18])
	by dragon.pibit.ch (Postfix) with ESMTPSA id 1B1F42140268
	for <nbd@other.debian.org>; Thu, 18 Jan 2024 11:46:38 +0100 (CET)
Message-ID: <5dd9746e-de8b-4936-95b6-bdffb82d6fad@pep-project.org>
Date: Thu, 18 Jan 2024 11:46:36 +0100
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
To: nbd@other.debian.org
Content-Language: de-DE, en-US
From: Lars Rohwedder <roker@pep-project.org>
Subject: Feature request: nbd-server serves multiple (autogenerated) files in
 directory hierarchy
Autocrypt: addr=roker@pep-project.org; keydata=
 xsDVBGCVZYIBDECv6bZ9vWKauYcvrF3WL7qRhQOPnIjcpkxUbVZHdehM+4EY4tYrzFu1l/5l
 wr09cewM3TDoSKKmEG+rpiTMKevRg9MDidJrUeq4A34FNHnfmyzJXJf4Rm0xfE7k1OguLXDp
 EXA6SNCfpbZdBtCPuwBo/dJl4JiAAnOWh0mfrabGSU3s3AydZ9UBKzjN+e4hScpjX8HJIyXT
 V3DybSky6RQ90SYfqSHLckMhUAur1T58edrtOyl2h+39RVi6kpf8eoy1gNRzbCDE2svJ8kg0
 y6sU5iuRD6ysW4OYn8IMRXZl5pLiiV9zlbjmbQl6VxctKc8tydMecN1YPyUa3i/L1MyUXGfc
 vxliSGfUXZUw/RXxo1RGUDMffUua0D7r5NwYIlnpkA+nMC8nKe85NKV70TD/lXs1YirImONQ
 MQhMSvdS8FOBHyE/yoMlWu4RzkCwuKXrkHrrFkX+AMWoZo65YMgtO1uB6BGQbeiC8VAKwzXu
 AStbcntgayMsY9QZXrIxKgpe3xPmzGyT4QARAQABzSlMYXJzIEguIFJvaHdlZGRlciA8cm9r
 ZXJAcGVwLXByb2plY3Qub3JnPsLBHAQTAQgAPhYhBIL4Tcc44oxO3aDGo89uC/LDP6CeBQJl
 pY1qAhsDBQkI0rpuBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEM9uC/LDP6CeI6IMPi/a
 +u9eqwg9F1vDOf0DeUlhGjdneMz2+0Yw9btE8HZjo6En0sAHFxzZlrmblwt3s5TIbtnECXTi
 Aa2hEt4PbAz5Ifeb6u+H0MutgXqrh6pkOka4RMEerm1Afkfpt5ZclKEe0UQXbmwdMhdJ76Ey
 BLzoRGEDVOpJlFIbiOVBnSy4ks7FFQKoED2E7s7laFe+EBjkCuJPL1Uq5jd3PpT7z2Rvr0ui
 TXh+jTHQ35tOba5AqXVVjiY6xlEQbKawPK/aPxnmEN8w29b+nfgTJr3CPlKmRLSn/S84aKxj
 kbB/5XfFvHhGUHZoZ0CMEatE+TOx87Tytc+t6Ahm1Qer6m0omfLBt4ZtZ6ygpFbvSyCn9z/p
 yHNUEaxE35fs76pgluUj5t4yNZde/vWLf4W83xlZWjPMFFWyt31+sdooKase1MdatjAbQvYx
 m1FFNpobAt5cijlmNWYa35l/aeZvk21n1aJZBhJAShXWDl9j2+9xaEEr23TRpw/2Mrqq4B0y
 IFSg44YTSVKjaCkHzsDVBGCVZYIBDEC9jkGR4HCZvcaNT/veGmoxoDkJSWroQOjnnEtJcsey
 JgcKYHFPKyueoVRD66xb/O0kMZMClxZxpnp5vv6NKSoIs6tZftmWm5ks0P++xybS3fvivjWz
 8ph5QUdjH1mfVFJxgvxtRlCP/KeaU5tpIFB8pZh5Qcvg/vtnvcb6jY39SQDVlkkUjKx2zSkx
 HOK2E6OWgKg+IIzGY1yBskNDvHPopzLcB8jWXE0hS6QDRtJIVaee505zN4L8I2RfV5yfoK4f
 gGshcMcYIwV8mL0Svkd1deRuBjjUGwfkiJeEPgdVCcP+KOYsT7dF0mJkDxUwRhLHwQr/Epbo
 ou19CDEnB4rs73H7nvtgjbGTc/2tS47g6mXlkQaYV7kkVsmGK5j1A0tPsw7yFPEhlg6FPWdy
 5QbXQr9lX9KiSckm6Pzf6W4Ax88IZo3KLcf/X+Ynx9LmCe6XPng0q/dCLxqOiX8nq6hTtVad
 RSDcTw8IRCYVAfeZWoPkIwfF2IUSY2MELM0AI57H6UV2sGOQiwARAQABwsEEBBgBCAAmFiEE
 gvhNxzjijE7doMajz24L8sM/oJ4FAmWljWsCGwwFCQjSum4ACgkQz24L8sM/oJ4j/Aw+LSO3
 op62JdPBR2zX81x83lpxg2dZbvwdIbaoCrxFl1LTuiZcDHF4pA1elcuVBfG15xMZiW7/iE7M
 YqMuRmxIdBP5f2VcU14igr0Hlsg3oZiClPUH2IdXUa7ETccOR6Ixm4tt2Mei4ruomuMdDDgL
 KklZsFSUawXJfSKVRxvsgjyR4ohaJfFh3NOZHV+0i8KPMZwdS2N0WmOGYPitSCAw6N/JQsiz
 Oq7G3Sf+VF6S4+6deN8hwwbQRcp6tMLmbVjo58dsLm9we3QIhyWv8i0hA6W1PlR2m7EFZRVu
 6o7Uh2VPx7o2VD3xl56kn5ZiENBAqzy6PFpIleSgeRQ2Fr91J/sXSIcsrpZTEoExHKnar2dL
 +J3EeMoXjEQSbq53MMq/Hl776/dVl1vQZCzzDd8sCTSX5qYpNF3FMh9EdWVj/OAXua9bI8it
 A3JE7zCQiL0HgM/Lgj5Y2l314axzq6L9YL1ZSxohPRksSUrF/Irx5u9HUn/XDC5D6fYi7L54
 GIaZVwoJisucuww=
Organization: =?UTF-8?B?8J+Ukg==?=
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="------------VfwV5w54erbz50EwBMCedJbM"
X-Rc-Virus: 2007-09-13_01
X-Rc-Spam: 2008-11-04_01
Resent-Message-ID: <zoVkIsKEZfM.A.dDE.gGQqlB@bendel>
Resent-From: nbd@other.debian.org
X-Mailing-List: <nbd@other.debian.org> archive/latest/2714
X-Loop: nbd@other.debian.org
List-Id: <nbd.other.debian.org>
List-URL: <https://lists.debian.org/nbd/>
List-Post: <mailto:nbd@other.debian.org>
List-Help: <mailto:nbd-request@other.debian.org?subject=help>
List-Subscribe: <mailto:nbd-request@other.debian.org?subject=subscribe>
List-Unsubscribe: <mailto:nbd-request@other.debian.org?subject=unsubscribe>
Precedence: list
Resent-Sender: nbd-request@other.debian.org
List-Archive: https://lists.debian.org/msgid-search/5dd9746e-de8b-4936-95b6-bdffb82d6fad@pep-project.org
Resent-Date: Thu, 18 Jan 2024 10:46:56 +0000 (UTC)

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--------------VfwV5w54erbz50EwBMCedJbM
Content-Type: multipart/mixed; boundary="------------9SSM0KWfqOzzNYWnuAEJeWCx";
 protected-headers="v1"
From: Lars Rohwedder <roker@pep-project.org>
To: nbd@other.debian.org
Message-ID: <5dd9746e-de8b-4936-95b6-bdffb82d6fad@pep-project.org>
Subject: Feature request: nbd-server serves multiple (autogenerated) files in
 directory hierarchy

--------------9SSM0KWfqOzzNYWnuAEJeWCx
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: base64

SGkgdGhlcmUsDQoNCkknZCBsaWtlIHRvIGhhdmUgKGFuZCB0byBpbXBsZW1lbnQpIHRoZSBm
b2xsb3dpbmcgZmVhdHVyZToNCg0KbmJkLXNlcnZlciBzaGFsbCBiZSBhYmxlIHRvIHVzZSBh
biAoYXV0by1nZW5lcmF0ZWQpIHNldCBvZiBtdWx0aXBsZSANCmZpbGVzIGluIGEgZGlyZWN0
b3J5IGhpZXJhcmNoeS4NCg0KSW4gZGV0YWlsOg0KDQoxLiBjb25maWcgZmlsZSBjb250YWlu
cw0KICAgKiB0aGUgYmFzZSBkaXJlY3RvcnksDQogICAqIHRoZSB0b3RhbCBzaXplIG9mIHRo
ZSBleHBvcnRlZCBibG9jayBkZXZpY2UsDQogICAqIGhlICJjaHVuayBzaXplIiAoPXNpemUg
b2YgZWFjaCBmaWxlKSBhbmQNCiAgICogaG93IG1hbnkgZmlsZXMvc3ViZGlycyBhcmUgc2hh
bGwgYmUgc3RvcmVkIHBlciBkaXJlY3RvcnkgYXQgbWF4aW11bS4NCg0KMi4gSWYgdGhlIG51
bWJlciBvZiAiY2h1bmsiIGZpbGVzIGV4Y2VlZHMgdGhlIG51bWJlciBvZiBhbGxvd2VkICJm
aWxlcyANCnBlciBkaXJlY3RvcnkiLCB0aGV5IGFyZSBkaXN0cmlidXRlZCBpbiBzdWIgZGly
ZWN0b3JpZXMuDQoNCjMuIHRoZSBuYmQtc2VydmVyIGNyZWF0ZXMgZmlsZXMgJiBzdWIgZGly
ZWN0b3JpZXMgb24gZGVtYW5kIHdoZW4gZGF0YSANCmFyZSB3cml0dGVuIHRvIHRoZSBleHBv
cnRlZCBibG9jayBkZXZpY2UuIFJlYWRzIGZyb20gbm9uLWV4aXN0ZW50IGZpbGVzIA0KYXJl
IGNvbnNpZGVyZWQgYXMgbnVsbCBieXRlcy4NCg0KNC4gSWYgdGhlIGJsb2NrIGRldmljZSBy
ZWdpb24gY292ZXJlZCBieSBhIGNodW5rIGZpbGUgaXMgInRyaW1tZWQiIA0KYW5kL29yIGNv
bXBsZXRlbHkgZmlsbGVkIHdpdGggbnVsbCBieXRlcyB0aGUgY2h1bmsgZmlsZSBtaWdodCBi
ZSBkZWxldGVkIA0KYXV0b21hdGljYWxseSBieSB0aGUgbmJkLXNlcnZlciAobWlnaHQgYmUg
ZG9uZSBsYXp5KS4NCg0KNS4gdGhlICJuYW1pbmcgY29udmVudGlvbiIgb2YgdGhlIGZpbGUg
YW5kIGRpcmVjdG9yeSBuYW1lcyBzaGFsbCBiZSANCmltcGxlbWVudGVkIGluIGEgc2luZ2xl
IGZ1bmN0aW9uIGFuZCBtaWdodCBiZSBjb25maWd1cmFibGUgaW4gbGF0ZXIgDQp2ZXJzaW9u
cy4gVGhlIGluaXRpYWwgdmVyc2lvbiBjYW4ganVzdCB1c2UgZGVjaW1hbCBudW1iZXJzIGFz
IGRpcmVjdG9yeSANCm5hbWVzIGFuZCBudW1iZXIrIi5iaW4iIGFzIGZpbGUgbmFtZXMuDQoN
Cg0KU29tZSBleGFtcGxlczoNCg0KQ2FzZSBBOiAxIEdpQiBkZXZpY2Ugc2l6ZSwgMSBNaUIg
Y2h1bmsgc2l6ZSwgMjAwMCBub2RlcyBwZXIgZGlyZWN0b3J5Og0KICAgIC0+IDEwMjQgY2h1
bmtzIC0+IGZpdCBpbiBvbmUgZGlyZWN0b3J5Lg0KICAgICRCQVNFRElSLzAwMDAuYmluDQog
ICAgLi4uDQogICAgJEJBU0VESVIvMTAyMy5iaW4NCg0KQ2FzZSBCOiAxIFRpQiBkZXZpY2Ug
c2l6ZSwgNCBNaUIgY2h1bmsgc2l6ZSwgMjAwMCBub2RlcyBwZXIgZGlyZWN0b3J5Og0KICAg
IC0+IDI2MjE0NCBjaHVua3MgLT4gaGllcmFyY2h5IGRlcHRoIG9mIGNlaWwobG9nKDI2MjE0
NCkvbG9nKDIwMDApKT0yLg0KICAgIGNodW5rICMwOiAkQkFTRURJUi8wMDAvMDAwMC5iaW4N
CiAgICAuLi4NCiAgICBjaHVuayAjMTk5OTogJEJBU0VESVIvMDAwLzE5OTkuYmluDQogICAg
Y2h1bmsgIzIwMDA6ICRCQVNFRElSLzAwMS8wMDAwLmJpbg0KICAgIC4uLg0KICAgIGNodW5r
ICMzOTk5OiAkQkFTRURJUi8wMDEvMTk5OS5iaW4NCiAgICAuLi4NCiAgICBjaHVuayAjMjYy
MTQzOiAkQkFTRURJUi8xMzEvMDE0My5iaW4gIChpZiBJIGNhbGN1bGF0ZWQgY29ycmVjdGx5
KQ0KDQpDYXNlIEM6IDEwIFRCIGRldmljZSwgNjQgS2lCIGNodW5rcywgMTAwMCBub2RlcyBw
ZXIgZGlyZWN0b3J5Og0KICAgIC0+IDE2Nyc3NzInMTYwIGNodW5rcyAtPiBoaWVyYXJjaHkg
ZGVwdGg6IDMuDQogICAgY2h1bmsgIzA6ICAkQkFTRURJUi8wMDAvMDAwLzAwMC5iaW4NCiAg
ICAuLi4NCiAgICBjaHVuayAjMTY3NzcyMTYwOiAkQkFTRURJUi8xNjcvNzcyLzE2MC5iaW4N
Cg0KDQpQbGVhc2UgdGVsbCBtZSB5b3VyIG9waW5pb24sIGlkZWFzIGFuZCBzdWdnZXN0aW9u
cyBmb3IgdGhpcyBmZWF0dXJlLg0KDQpHcmVldGluZ3MsDQoNCgkJTGFycyBSb2h3ZWRkZXIN
Cg==

--------------9SSM0KWfqOzzNYWnuAEJeWCx--

--------------VfwV5w54erbz50EwBMCedJbM
Content-Type: application/pgp-signature; name="OpenPGP_signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="OpenPGP_signature.asc"

-----BEGIN PGP SIGNATURE-----

wsEBBAABCAAjFiEEgvhNxzjijE7doMajz24L8sM/oJ4FAmWpAYwFAwAAAAAACgkQz24L8sM/oJ5N
ngxAgBcHScehZ5FtPDw+XheJ7h5fnSAYyAxGog02dfLkzssAsE/0xI6PC8KvAWrctc+pyflWCS4v
4uBSgK4y77QsaANjOCd+MBhaMHRPL+QQlrase13dsAYjQU4Ee14OWhyCiixgogu28p7dU4d6FBTz
1iOT0RV4c6v22BHapBGOKXWdsNqDECXg8wZ57uh4i2ITGApBiYpo261ZYkjERGtf7azq5Ke5ZTJ7
HGS/t5YgDZ9EfnB/S6RzVtOz28er3+HnsQ6ELSMM4zDwBrZWj/frQMll3CmaRjtIOrWBXFQmZ1b5
m9D7yM4kroAtHK0H8sB4vC1a4wOhNgMS6sv9ry5N9DrKsce3cTHhVbS/Av6dhginmQi16AkRRHC2
KDUzc0mKWmzPN8g9K1JxHmz7qnsdFFltENPpOMk1/nFzbBHWGluImYxDcioAxf2WRRXmre4Yn6xe
DwxoflN2ZS53k563pEEqOJ5Kqk6AtD16SMgY+vJ8EBfQ+5SoSGjslxZTKSZARw5FlT92su8=
=YEzc
-----END PGP SIGNATURE-----

--------------VfwV5w54erbz50EwBMCedJbM--

