Return-Path: <bounce-nbd=lists+nbd=lfdr.de@other.debian.org>
X-Original-To: lists+nbd@lfdr.de
Delivered-To: lists+nbd@lfdr.de
Received: from bendel.debian.org (bendel.debian.org [IPv6:2001:41b8:202:deb:216:36ff:fe40:4002])
	by mail.lfdr.de (Postfix) with ESMTPS id 57E378447C3
	for <lists+nbd@lfdr.de>; Wed, 31 Jan 2024 20:06:26 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
	by bendel.debian.org (Postfix) with QMQP
	id DCC5220607; Wed, 31 Jan 2024 19:06:25 +0000 (UTC)
X-Mailbox-Line: From nbd-request@other.debian.org  Wed Jan 31 19:06:25 2024
Old-Return-Path: <w@uter.be>
X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on bendel.debian.org
X-Spam-Level: 
X-Spam-Status: No, score=-11.3 required=4.0 tests=DKIM_SIGNED,DKIM_VALID,
	DKIM_VALID_AU,DKIM_VALID_EF,LDOSUBSCRIBER,LDO_WHITELIST,
	T_SCC_BODY_TEXT_LINE autolearn=unavailable autolearn_force=no
	version=3.4.2
X-Original-To: lists-other-nbd@bendel.debian.org
Delivered-To: lists-other-nbd@bendel.debian.org
Received: from localhost (localhost [127.0.0.1])
	by bendel.debian.org (Postfix) with ESMTP id 8769F205BA
	for <lists-other-nbd@bendel.debian.org>; Wed, 31 Jan 2024 19:06:14 +0000 (UTC)
X-Virus-Scanned: at lists.debian.org with policy bank en-lt
X-Amavis-Spam-Status: No, score=-7.21 tagged_above=-10000 required=5.3
	tests=[BAYES_00=-2, DKIM_SIGNED=0.1, DKIM_VALID=-0.1,
	DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1, LDO_WHITELIST=-5,
	T_SCC_BODY_TEXT_LINE=-0.01] autolearn=ham autolearn_force=no
Received: from bendel.debian.org ([127.0.0.1])
	by localhost (lists.debian.org [127.0.0.1]) (amavisd-new, port 2525)
	with ESMTP id mj3Fdf6Mlhnw for <lists-other-nbd@bendel.debian.org>;
	Wed, 31 Jan 2024 19:06:06 +0000 (UTC)
X-policyd-weight: using cached result; rate: -4.6
Received: from lounge.grep.be (lounge.grep.be [IPv6:2a01:4f8:200:91e8::2])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA256)
	(Client did not present a certificate)
	by bendel.debian.org (Postfix) with ESMTPS id 8F33520591
	for <nbd@other.debian.org>; Wed, 31 Jan 2024 19:06:06 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=uter.be;
	s=2021.lounge; h=In-Reply-To:Content-Type:MIME-Version:References:Message-ID:
	Subject:Cc:To:From:Date:Sender:Reply-To:Content-Transfer-Encoding:Content-ID:
	Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc
	:Resent-Message-ID:List-Id:List-Help:List-Unsubscribe:List-Subscribe:
	List-Post:List-Owner:List-Archive;
	bh=AzJcxUl1M3aBDpFzMl35RH1fm8XFoEZJSkP34jDGhGk=; b=kvnni60kGwU0gLbrVjJrksD7qv
	hZQom/uOY5lewpH2NUP8tL1NUrxwNnqZmPv6J8UMlOFyhIdkphgzZZ2A8NIOX4GCI9aES9/yd1Qw9
	wqOc4SaKS5iPv2BzYmpmV1v6ctisMZ/80G85U5cOt+gph2D/iX0OuQBMc/VlybijQP1P3OHnxIrpO
	SY066ykQxrTMZrsuSdU/IphuJ8nNDTIq3ohB6qIZlXDS8Zp6E9Rr6SMK7PLU0YY/bgXvT8CvhbTxu
	I9E2JvoAoIsqLfeqP/Kket3BHOYOtz+ZftKqfzhwP4/bSDwJOBEpIoPzLzNmv+R2JcitR4w0uuswJ
	rZ+q6Tsw==;
Received: from [213.172.149.157] (helo=pc220518)
	by lounge.grep.be with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.96)
	(envelope-from <w@uter.be>)
	id 1rVFuN-006jUg-2i;
	Wed, 31 Jan 2024 20:06:03 +0100
Received: from wouter by pc220518 with local (Exim 4.97)
	(envelope-from <w@uter.be>)
	id 1rVFu8-00000001SZf-2G56;
	Wed, 31 Jan 2024 21:05:48 +0200
Date: Wed, 31 Jan 2024 21:05:48 +0200
From: Wouter Verhelst <w@uter.be>
To: Lars Rohwedder <roker@pep-project.org>
Cc: nbd@other.debian.org
Subject: Re: Feature request: nbd-server serves multiple (autogenerated)
 files in directory hierarchy
Message-ID: <ZbqaDMf-VqRacj4p@pc220518.home.grep.be>
References: <5dd9746e-de8b-4936-95b6-bdffb82d6fad@pep-project.org>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <5dd9746e-de8b-4936-95b6-bdffb82d6fad@pep-project.org>
X-Speed: Gates' Law: Every 18 months, the speed of software halves.
Organization: none
X-Rc-Virus: 2007-09-13_01
X-Rc-Spam: 2008-11-04_01
Resent-Message-ID: <yECygsDIDbC.A.wpD.xopulB@bendel>
Resent-From: nbd@other.debian.org
X-Mailing-List: <nbd@other.debian.org> archive/latest/2722
X-Loop: nbd@other.debian.org
List-Id: <nbd.other.debian.org>
List-URL: <https://lists.debian.org/nbd/>
List-Post: <mailto:nbd@other.debian.org>
List-Help: <mailto:nbd-request@other.debian.org?subject=help>
List-Subscribe: <mailto:nbd-request@other.debian.org?subject=subscribe>
List-Unsubscribe: <mailto:nbd-request@other.debian.org?subject=unsubscribe>
Precedence: list
Resent-Sender: nbd-request@other.debian.org
List-Archive: https://lists.debian.org/msgid-search/ZbqaDMf-VqRacj4p@pc220518.home.grep.be
Resent-Date: Wed, 31 Jan 2024 19:06:25 +0000 (UTC)

Hi Lars,

Sorry for the late reply; I'm a bit busy as a co-organizer of FOSDEM
these days, and I haven't gotten around to looking at my nbd mailbox in
a while...

On Thu, Jan 18, 2024 at 11:46:36AM +0100, Lars Rohwedder wrote:
> Some examples:
> 
> Case A: 1 GiB device size, 1 MiB chunk size, 2000 nodes per directory:
>    -> 1024 chunks -> fit in one directory.
>    $BASEDIR/0000.bin
>    ...
>    $BASEDIR/1023.bin
> 
> Case B: 1 TiB device size, 4 MiB chunk size, 2000 nodes per directory:
>    -> 262144 chunks -> hierarchy depth of ceil(log(262144)/log(2000))=2.
>    chunk #0: $BASEDIR/000/0000.bin
>    ...
>    chunk #1999: $BASEDIR/000/1999.bin
>    chunk #2000: $BASEDIR/001/0000.bin
>    ...
>    chunk #3999: $BASEDIR/001/1999.bin
>    ...
>    chunk #262143: $BASEDIR/131/0143.bin  (if I calculated correctly)
> 
> Case C: 10 TB device, 64 KiB chunks, 1000 nodes per directory:
>    -> 167'772'160 chunks -> hierarchy depth: 3.
>    chunk #0:  $BASEDIR/000/000/000.bin
>    ...
>    chunk #167772160: $BASEDIR/167/772/160.bin

This sounds a lot like the "treefiles" feature in nbd-server. Have you
looked at that? See "man 5 nbd-server" and search for "treefiles".

If that doesn't do what you're looking for, I'm always willing to look
at patches ;-)

-- 
     w@uter.{be,co.za}
wouter@{grep.be,fosdem.org,debian.org}

I will have a Tin-Actinium-Potassium mixture, thanks.

